In [2]:
import numpy as np
import matplotlib.pyplot as plt

### What is layer of neurons?
Nothing, just a group of single neurons

## Note
* Every neuron in a layer takes same inputs.
* Each neuron has its own set of weights for inputs.

  Example:
    * **Neuron N1** has weight 1.2 associated with input 1
    * **Neuron N2** can have weight -0.4 associated with input 1

* Each neuron has its own bias.

In [4]:
# Inputs
inputs = np.arange(1,5)
inputs

array([1, 2, 3, 4])

Let's say we have **5 neurons**

In [12]:
# Weights associated with 5 neurons
# For 4 inputs and 5 neurons we need 20 weights, 4 weights for each neuron
weights = np.random.uniform(-1,1,20).reshape(5,4)
weights

array([[-0.10477064, -0.55485   , -0.61945263,  0.14975784],
       [ 0.38427067, -0.05743179, -0.90747222, -0.38065549],
       [ 0.75840105,  0.99158276, -0.72577153, -0.40800767],
       [-0.35518002,  0.7190426 ,  0.25868816, -0.03027441],
       [ 0.54145836, -0.99925238, -0.99589685,  0.20253194]])

In [29]:
# Bias
bias = np.random.randint(1, 6, 5)
bias

array([2, 4, 5, 5, 1])

### How a layer works?

#### Output of single neuron
$$
\text{Output of single neuron} = \sigma(\sum (inputs * weights) + bias)
$$

#### Layer output is just sum of outputs of neurons
$$
\text{Layer output}= \sum_{i = 1}^N \text{Outputs of N neurons}
$$



In [31]:
# Output of each neuron without using activation function for the time being
o1 = np.sum(inputs * weights[0]) + bias [0]
o2 = np.sum(inputs * weights[1]) + bias [1]
o3 = np.sum(inputs * weights[2]) + bias [2]
o4 = np.sum(inputs * weights[3]) + bias [3]
o5 = np.sum(inputs * weights[4]) + bias [4]
o1, o2, o3, o4, o5

(-0.473797172618565,
 0.024368460258476166,
 3.9322213024441326,
 6.7378720370109715,
 -2.6346092038000046)

In [38]:
# Output of layer
layer_output = np.sum([o1,o2,o3,o4,o5])
layer_output

7.586055423295011

### Calculating using Matrix multiplication
$$
\text{Outputs of neurons} = \sigma(inputs~*~weights^T)
$$
$$
\text{Layer output}= \sum_{i = 1}^N \text{Outputs of neurons}
$$

In [39]:
neuron_outputs = np.dot(inputs, weights.T) + bias
layer_output = neuron_outputs.sum()
print("Outputs of neurons\n",neuron_outputs)
print("Output of layer\n", layer_output)

Outputs of neurons
 [-0.47379717  0.02436846  3.9322213   6.73787204 -2.6346092 ]
Output of layer
 7.58605542329501


### Summary
$$
\text{Output of neuron} = \sigma(inputs~*~weights^T + bias)
$$

$$
\text{Layer output} = \sum{\sigma(inputs~*~weights^T + bias)}
$$

#### Code
```python
neuron_outputs = np.dot(inputs, weights.T) + bias
layer_output = np.sum(np.dot(inputs, weights.T) + bias)
```

### We just created a Fully connected network &#x1F600;